-- AlterTable
ALTER TABLE `vistoria_eventos` MODIFY `tipo` ENUM('CRIADA', 'CONVITE_ENVIADO', 'COMPLEMENTO_SOLICITADO', 'LINK_ABERTO', 'EXECUCAO_INICIADA', 'FOTO_REMOVIDA', 'CONCLUIDA', 'APROVADA', 'AVISO_ENVIADO', 'LAUDO_GERADO', 'LAUDO_ENVIADO', 'LAUDO_ABERTO') NOT NULL;
